---
title: "Deliverable1"
output: github_document
---



## R Markdown


```{r dataimport}
library(tidyverse)
KSData2018 <- read_csv("kickstarter-projects/ks-projects-201801.csv")#, col_types = cols(state = col_factor()))
problems(KSData2018)

KSData2018
```


```{r transformations}
KSData2018 <- KSData2018 %>% mutate(prop_raised_goal = usd_pledged_real/usd_goal_real)



#Filtering by prop < 2 only eliminates ~20,000 entries of the 378,654 entries
KSDataFiltered <- KSData2018 %>% filter(prop_raised_goal < 2 & (state == "failed" | state == "successful")) %>% group_by(main_category, state) %>% summarize(state_count = n()) %>%
  ungroup() %>% group_by(main_category) %>% mutate(total = sum(state_count)) %>% mutate(succ_prop = ifelse(state == "successful", state_count/total, 1-state_count/total)) %>% ungroup()


KSDataFiltered
#KSData2018



## Including Plots

#You can also embed plots, for example:

ggplot(KSDataFiltered) + geom_bar(aes(x = main_category, y = state_count, fill = state), stat = "identity", position=position_dodge()) + theme(axis.text.x = element_text(size = 10, angle = 45, hjust = 1)) + labs(title = "Main Category vs. Successes & Failure Count by Category", x = "Category", y = "Count")

```


We chose ot filter out data points with a proportion of raised to goal greater than 2 as there were many outliers with a proportion reaching as high as 10^8. Upon inspection we found
these data points were from Kickstarters where the project owner set the goal to $1 and proceeded to raise millions.
Doing this filtered out ~20,000 entries of the 378,654 entries
```{r transformations2}
KSDataFiltered2 <- KSData2018 %>% mutate(prop_raised_goal = usd_pledged_real/usd_goal_real) %>% filter(prop_raised_goal < 2)
#KSDataFiltered2

ggplot(KSDataFiltered2) + geom_boxplot(aes(x = main_category, y = prop_raised_goal)) + theme(axis.text.x = element_text(size = 10, angle = 45, hjust = 1)) +
  labs(title = "Propotion of Raised to Goal by Category", x = "Main Category", y = "Proportion of Raised to Goal")



```